spring.application.name=MyCRM


#Database details
spring.datasource.url=jdbc:postgresql://localhost:5432/mycrm
spring.datasource.username=crm_postgres_user
spring.datasource.password=crm_pg_p06
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true


#Multipart file size
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB