spring.application.name=MyCRM


#Database details
spring.datasource.url=jdbc:postgresql://localhost:5432/mycrm
spring.datasource.username=crm_postgres_user
spring.datasource.password=crm_pg_p06
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true

#learn
spring.jpa.properties.hibernate.enable_lazy_load_no_trans=true
spring.jpa.properties.hibernate.jdbc.batch_size=200
spring.jpa.properties.hibernate.order_inserts=true
spring.jpa.properties.hibernate.generate_statistics=true
spring.jpa.properties.hibernate.proc.param_null_passing=true
spring.jpa.properties.hibernate.dialect.use_legacy_lock_hints=true
logging.level.org.hibernate.SQL=TRACE
logging.level.org.hibernate.stat=TRACE
logging.level.org.hibernate.session.metrics=DEBUG



#Multipart file size
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB